language: node_js
node_js: 10.13.0
cache:
  yarn: true
  directories:
  - "./.cache"
  - "./public"
install: yarn install
before_script: sed -i "s|'/',|'/gatsby-starter-plone/',|" ./gatsby-config.js
script: "./node_modules/.bin/gatsby build --prefix-paths"
deploy:
  provider: pages
  github_token: "$GITHUB_TOKEN"
  local_dir: "./public"
  target_branch: gh-pages
  keep_history: false
  skip_cleanup: true
  on:
    branch: master
env:
  global:
    secure: T0OE9oXKiFhXR4s0nvjXxh1itU5V0kkqfBZ0di7LNcyAccCXbjKgZXGLe3i5r+O1MfeYGNZNpJwARGI+81NuXJ8ekKpG6298ViHh3G6cjzH23CueIlikVmaHG4ddkIblDREQCzRYXwTSwllaAFn56gdBqRmgFfqQNaKfboRqirVI4fdnP3/ROTIOrtfStjDbaNE3RLZ79noAFvC3xMZ7euH8b4ajwbVIA/3+hdo4u9V/8xvmC6X3/teqJNPdLtSgMMVcr4ZM0Sidi3deFvkNH+c1JtU96w9bJ/ghnd7AdOghmAWeTcHYSyv9lQv3YGDeAjyYCWxStxlp/F3eTS/DYDbTNoZj8oQL/OnJA/u81pJxnBFuIN4w2nwKz2CJefmoBuYBGKPMYmAtRu837uDPtmuF3Ck3In9GOniObDpItxxE63W90eKcg5EgegH/wauVFe/veQiiz5fNmU+flBtL4zJzjy2TEfvDMlVMHAy+kh4KYmn4g8YSCbVtIJ3uxdLtLhQKU3mC9XMLwTrIv1p7J2M2kklyQPfh581xjqr51QUI6sGQe2AOTskOAYD6WPFlMnUhrNfZlM0RRk8bcIDJdcSR9O/u0Y8VMZjKieHV5L2FeacCqmqHfLrt/yc65ue0xFqbFaqDCQK2ch8vGfWBEHJr6iQcRYy3CMrWkHYBXXo=
